<?php
 $status = [
        'CREATED' => '创建',
        'PENDING' => '进行中',
        'FINISHED' => '完成',
    ];
?>
<?php if(isset(static::$_responses['message']) && !empty(static::$_responses['message'])):?>
    <div class="alert <?=static::$_responses['success'] ? 'alert-success': 'alert-danger'?>">
        <?=static::$_responses['message']?>
    </div>
<?php endif;?>

<section class="container">
    <header><h2>热门推荐</h2></header>
    <article>
        <footer>

            <?php if(count(static::$_responses['contracts'])):?>
                <table class="table table-hover text-center">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">标题</th>
                        <th scope="col">奖励</th>
                        <th scope="col">状态</th>
                        <th scope="col">发布时间</th>
                        <th scope="col">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach(static::$_responses['contracts'] as $contact):?>
                        <tr>
                            <th scope="row"><?=$contact->id?></th>
                            <td><?=$contact->title?></td>
                            <td><?=$contact->reward?></td>
                            <td><?=$status[$contact->status]?></td>
                            <td><?=$contact->created_at?></td>
                            <td>
                                <a class="btn btn-primary" href="<?=static::getUrl('contract/view/') . $contact->id;
                                ?>">查看</a>

                                <?php if(!$contact->locked && (!isset(static::$_responses['current_user']) || (isset(static::$_responses['current_user']) && static::$_responses['current_user']['type'] != 'enterprise'))):?>
                                    <a class="btn btn-success" href="<?=static::getUrl('contract/accept/'). $contact->id;?>">接受</a>
                                <?php endif;?>

                                <?php if (isset(static::$_responses['current_user']) && $contact->customer_id ==static::$_responses['current_user']['id'] && $contact->locked) :?>
                                    <a class="btn btn-success" href="<?=static::getUrl('contract/finish/').$contact->id;?>">确认</a>
                                <?php endif;?>


                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            <?php else:?>

                <p class="text-center">暂无信息</p>

            <?php endif;?>

    </article>

</section>