<section class="container">
    <article>
        <header><h2>找回密码</h2></header>
        <footer>
            <div class="messages">
                <?php if(isset(static::$_responses['message']) && !empty(static::$_responses['message'])):?>
                    <div class="alert <?=static::$_responses['success'] ? 'alert-success': 'alert-danger'?>">
                        <?=static::$_responses['message']?>
                    </div>
                <?php endif;?>
            </div>

            <?php if (isset(static::$_responses['reset_password'])):?>
                <form method="post" action="<?=static::getUrl('user/forgetpassword');?>">
                    <input type="hidden" name="forget[id]" value="<?=static::$_responses['user_id']?>"/>
                    <div class="input-text">
                        <input type="password" name="forget[password]" id="password" placeholder="请输入您的密码">
                    </div>
                    <p class="text-center"><button class="button-s1" type="submit">确认</button></p>
                </form>
            <?php else:?>
                <form method="post" action="<?=static::getUrl('user/forgetpassword');?>">
                    <div class="input-text">
                        <label for="email">请输入您的邮箱</label>
                        <input type="text" id="email" name="email" placeholder="邮箱" required>
                    </div>
                    <p class="text-center"><button class="button-s1" type="submit">发送</button></p>
                </form>
            <?php endif;?>
        </footer>
    </article>
</section>