<section class="container">

    <?php if(static::$_responses['message']):?>
        <div class="alert <?=static::$_responses['success'] ? 'alert-success':
            'alert-danger'?>">
            <?php if(static::$_responses['message']):?><?=static::$_responses['message']?><?php endif;?>
        </div>
    <?php endif;?>

    <article class="form-user-profil">
        <form method="post" action="<?=static::getUrl('user/profil');?>" enctype="multipart/form-data">
                <input type="hidden" name="profil[id]" value="<?=static::$_responses['current_user']['id']?>"/>
                <div class="input-text upload-avatar">
                    <label for="avatar">个人头像</label>
                    <?php if(!isset(static::$_responses['current_user']['avatar'])):?>
                        <img src="<?=static::getUrl('images/icons/account.png');?>"/>
                    <?php else:?>
                        <img src="<?=static::getUrl('images/avatars/'.static::$_responses['current_user']['avatar']);?>"/>
                    <?php endif;?>
                    <input type="file" id="avatar" name="profil[avatar]" value="上传">
                </div>
                <div class="input-text">
                    <label for="password">新密码</label>
                    <input id="password" type="password" name="profil[new_password]" placeholder="请输入密码">
                </div>
            <div class="input-text">
                <label for="password">新密码</label>
                <input id="password_confirmation" type="password" name="profil[password_confirmation]" placeholder="请输入密码">
            </div>
                <div class="input-text">
                    <label for="current_password">当前密码</label>
                    <input id="current_password" type="password" name="profil[old_password]" placeholder="当前密码">
                </div>
            <p class="text-center">
                <button class="button-s1 button-color-s1" type="submit" name="profil[button]"
                        value="delete">删除我的账户</button>
                <button class="button-s1" type="submit" name="profil[button]"  value="update">更新我的资料</button>
            </p>
        </form>
    </article>
</section>